runtime: nodejs20

env_variables:
  MONGODB_URI: mongodb+srv://atlas_db_user:HLogUF8zEjnT3OKZ@cluster0.ghngg63.mongodb.net/recipe-planner?retryWrites=true&w=majority&appName=Cluster0
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10